# Site settings
title: CDRH Development Blog
email: kdalziel2@unl.edu
description: > # this means to ignore newlines until "baseurl:"
    Ideas and updates from the development team at the
    Center for Digital Research in the Humanities
    and the University of Nebraska-Lincoln.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cdrh.github.io" # the base hostname & protocol for your site
twitter_username: CDRH_UNL
github_username:  CDRH

# Gems
gems:
  - jekyll-paginate
  - jekyll-redirect-from

# Build settings
markdown: kramdown
paginate: 10               # number of posts per page
paginate_path: "/:num/"
