# Site settings
title: CDRH Development Blog
email: kdalziel2@unl.edu
description: > # this means to ignore newlines until "baseurl:"
    Updates and ideas from the development team at the
    Center for Digital Research in the Humanities at the
    University of Nebraska-Lincoln.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown   # default markdown
pygments: true  # code syntax highlighter
